export type Locale = "pt" | "en";
export type PageKind = "home" | "practice" | "results" | "about" | "team";
export const copy = {
    pt: {
        nav: ["Início", "Áreas de atuação", "Resultados", "O escritório", "A equipa"], consult: "Agendar uma consulta", location: "Advocacia em Moçambique", intro: "Advogados e consultores em Moçambique.", lead: "Assessoria jurídica e representação de particulares e empresas em questões familiares, patrimoniais e comerciais.", explore: "Conheça a nossa atuação", scroll: "Explore o escritório", promise: "Assessoria jurídica para particulares e empresas.", promiseText: "Analisamos a sua situação, explicamos as opções legais e definimos consigo os próximos passos.", practiceTitle: "Áreas de atuação", practiceLead: "Consulte as áreas em que prestamos assessoria e representação jurídica.", teamTitle: "A nossa equipa", teamLead: "Conheça os advogados da ENA e as suas áreas de atuação.", aboutTitle: "O escritório ENA", aboutLead: "A ENA presta serviços de advocacia e consultoria jurídica a particulares e empresas em Moçambique.", resultsTitle: "O nosso trabalho", resultsLead: "Prestamos assessoria, negociamos acordos e representamos clientes em processos judiciais.", aboutLink: "Conheça a ENA", teamLink: "Conheça a equipa", allPractice: "Todas as áreas de atuação", approach: "Como trabalhamos", steps: ["Consulta inicial", "Análise jurídica", "Acompanhamento do processo"], stepText: ["Reunimos consigo para conhecer o assunto e os documentos relevantes.", "Avaliamos as opções legais e explicamos os procedimentos aplicáveis.", "Tratamos das diligências acordadas e informamos sobre o andamento do processo."], contactTitle: "Contacte o escritório", contactText: "Para agendar uma consulta, contacte-nos por telefone, email ou WhatsApp.", email: "Escreva-nos", phone: "Fale connosco", whatsapp: "Conversar pelo WhatsApp", rights: "Todos os direitos reservados.", principles: ["Análise jurídica", "Confidencialidade", "Direito moçambicano"], principleText: ["Analisamos os factos e os documentos antes de propor uma linha de atuação.", "Tratamos as informações dos clientes com discrição e respeito pelo sigilo profissional.", "Prestamos assessoria sobre a legislação aplicável em Moçambique."], outcomes: ["Litígios comerciais", "Direito de família", "Contratos e património", "Representação jurídica"], outcomeText: ["Defesa e negociação em conflitos empresariais e comerciais.", "Acompanhamento atento em questões de divórcio, guarda e sucessões.", "Apoio jurídico em contratos, transações e planeamento sucessório.", "Representação e assessoria jurídica em Moçambique."], resultsNote: "Cada caso depende das suas circunstâncias. Resultados anteriores não garantem resultados futuros.", profile: "Perfil do escritório", menu: "Abrir navegação", close: "Fechar navegação", skip: "Saltar para o conteúdo", message: "Olá, gostaria de agendar uma consulta."
    },
    en: {
        nav: ["Home", "Practice areas", "Our work", "The firm", "Our team"], consult: "Book a consultation", location: "Legal counsel in Mozambique", intro: "Lawyers and consultants in Mozambique.", lead: "Legal advice and representation for individuals and businesses in family, property and commercial matters.", explore: "View practice areas", scroll: "About the firm", promise: "Legal advice for individuals and businesses.", promiseText: "We review your situation, explain the legal options and agree on the next steps with you.", practiceTitle: "Practice areas", practiceLead: "See the areas in which we provide legal advice and representation.", teamTitle: "Our team", teamLead: "Meet the ENA lawyers and see their practice areas.", aboutTitle: "The ENA law firm", aboutLead: "ENA provides legal advice and representation to individuals and businesses in Mozambique.", resultsTitle: "Our work", resultsLead: "We advise clients, negotiate agreements and represent them in court proceedings.", aboutLink: "Meet ENA", teamLink: "Meet our team", allPractice: "All practice areas", approach: "How we work", steps: ["Initial consultation", "Legal review", "Case management"], stepText: ["We meet with you to discuss the matter and review relevant documents.", "We assess the legal options and explain the applicable procedures.", "We handle the agreed work and keep you informed of progress."], contactTitle: "Contact the firm", contactText: "To book a consultation, contact us by phone, email or WhatsApp.", email: "Write to us", phone: "Call us", whatsapp: "Chat on WhatsApp", rights: "All rights reserved.", principles: ["Legal review", "Confidentiality", "Mozambican law"], principleText: ["We review the facts and documents before recommending a course of action.", "We handle client information with discretion and respect professional confidentiality.", "We advise on the legislation applicable in Mozambique."], outcomes: ["Commercial disputes", "Family law", "Contracts and property", "Legal representation"], outcomeText: ["Representation and negotiation in corporate and commercial disputes.", "Legal advice on divorce, custody and succession matters.", "Legal guidance on contracts, transactions and estate planning.", "Legal representation and advisory services in Mozambique."], resultsNote: "Every case depends on its circumstances. Past results do not guarantee future outcomes.", profile: "Firm profile", menu: "Open navigation", close: "Close navigation", skip: "Skip to content", message: "Hello, I would like to book a consultation."
    }
};
export const practices = [
    { pt: "Litígios empresariais", en: "Corporate litigation", textPt: "Defesa e negociação em disputas corporativas e comerciais.", textEn: "Representation and negotiation in corporate and commercial disputes." },
    { pt: "Direito imobiliário", en: "Real estate", textPt: "Acompanhamento em compra, venda e contratos imobiliários.", textEn: "Guidance on property purchases, sales and real estate contracts." },
    { pt: "Direito de família", en: "Family law", textPt: "Apoio jurídico em questões de divórcio, guarda e sucessões.", textEn: "Legal advice on divorce, custody and succession matters." },
    { pt: "Direitos sucessórios", en: "Estate planning", textPt: "Estratégias para proteger património e gerir heranças.", textEn: "Strategies to protect assets and manage inheritances." },
    { pt: "Direito administrativo", en: "Administrative law", textPt: "Consultoria sobre licenças, recursos e processos administrativos.", textEn: "Counsel on licensing, appeals and administrative proceedings." },
    { pt: "Petróleo e gás", en: "Oil and gas", textPt: "Assessoria em exploração, produção, contratos e conformidade regulatória.", textEn: "Advice on exploration, production, contracts and regulatory compliance." },
    { pt: "Contencioso", en: "Litigation", textPt: "Representação em processos judiciais e resolução de conflitos.", textEn: "Representation in court proceedings and conflict resolution." },
    { pt: "Direito penal", en: "Criminal law", textPt: "Defesa estratégica e proteção dos seus direitos em processos criminais.", textEn: "Defense and representation in criminal proceedings." }
];
export const members = [
    { name: "Dra. Lizzy NK", initials: "LK", pt: "Direito de família", en: "Family law", image: undefined },
    { name: "Dr. Angelo NK", initials: "AK", pt: "Litígios empresariais", en: "Corporate litigation", image: "/Angelo.jpeg" },
    { name: "Dr. Jeff R.", initials: "JR", pt: "Direito imobiliário", en: "Real estate", image: undefined }
];
